config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("saas_02.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("saas_02.core.urls", namespace='api')),
    # path("api2/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

saas_02/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from saas_02.core import views
from django.contrib.auth.decorators import login_required


app_name = "core"
urlpatterns = [
    path("", login_required(TemplateView.as_view(template_name='pages/demo.html')), name='demo'),
    path("upload/", views.ImageRecognitionView.as_view(), name='image-recognition'),
    # path("demo/", views.FileUploadView.as_view(), name='file-upload-demo'),

    # Reset Email
    path("change-email/", views.ChangeEmailView.as_view(), name='change-email'),
    path("get-email/", views.GetUserEmailView.as_view(), name='get-email'),

    # password
    path("password/", login_required(TemplateView.as_view(template_name='pages/reset_password.html')), name='password'), # html page
    path("password-reset/", views.ResetPasswordAPIView.as_view(), name='password-reset'), # html page

    # api-key
    path("api-key/", login_required(TemplateView.as_view(template_name='pages/api-key.html')), name='api-key'), # html page

    # billing 
    path("billing/", login_required(TemplateView.as_view(template_name='pages/billing.html')), name='billing'), # billing page
    path("billing-detail/", views.UserBillingDetailsView.as_view(), name='billing-detail'), # return user's billing status 

    #stipe subscribe
    path("create-checkout-session/", views.CreateCheckoutSessionView.as_view(), name='create-checkout-session'), # return url checkout_session
    path("webhooks/stripe/", views.webhook, name='stripe-webhook'), # except stripe webhooks

    # cancel-subscription
    path("cancel-subscription/", views.CancelSubscriptionView.as_view(), name="cancel-subscription"),

#    loader
    path("loader/", login_required(TemplateView.as_view(template_name='pages/loader.html')), name='loader'), # billing page
]

saas_02/users/urls.py
from django.urls import path

from saas_02.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

saas_02/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

saas_02/core/views.py
import math
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.status import (HTTP_200_OK,
                                    HTTP_500_INTERNAL_SERVER_ERROR,
                                      HTTP_400_BAD_REQUEST,
                                      HTTP_405_METHOD_NOT_ALLOWED,
                                      HTTP_406_NOT_ACCEPTABLE,
                                      HTTP_303_SEE_OTHER)
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.authtoken.models import Token
from saas_02.core.serializers import (ChangePasswordSerializer,
                                       SubscribeSerializer,
                                         FileSerializer,
                                         ChangeEmailSerializer)
from django.contrib.auth import authenticate
from saas_02.core.models import TrackedRequest, Membership
from django.conf import settings
# from saas_02.core.image_detection import detect_faces
from saas_02.core.permissions import IsMember
from saas_02.core.models import Payment
from django.http import HttpResponse
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user_model
from rest_framework.throttling import UserRateThrottle
User = get_user_model()

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
import datetime
from stripe.error import SignatureVerificationError

def get_user_from_token(request):
    '''
    The function take the token in the request 
    then use the token to retrieve the User object with the same token
    '''
    # Retieve the token
    token = request.META['HTTP_AUTHORIZATION'].split()[1]
    # Rerieve the user object
    try:
        user = Token.objects.get(key=token).user
        return user
    except Exception as e:
        print('Could not retrieve the user based on the given token: ', e)

def get_type_display(type):
    return settings.MEMBERSHIP_CHOICES(type)

class ImageRecognitionView(APIView):
    permission_classes = (IsMember,)
    throttle_scope = 'uploads' # Maximum 20 requests per min
    def post(self, request, *args, **kwargs):
        user = get_user_from_token(request)
           
        if user.membership.type == 'M': 

            try :
                # Create new usage record  
                usage_record = stripe.SubscriptionItem.create_usage_record(
                    user.membership.stripe_subscription_item_id,
                    quantity=1,
                    timestamp=math.floor(datetime.datetime.now().timestamp()),
                    )
            except Exception as e:
                print("Error when creating usage record: ", str(e))
            

                                 
            tracked_request = TrackedRequest()
            tracked_request.user = user
            tracked_request.endpoint = '/api/upload/image-recognition/'
            tracked_request.usage_record_id = usage_record.id        
            tracked_request.save()
       

        
        # Check image size
        length = request.META.get('CONTENT_LENGTH')
        if int(length) > 5000000:
            return Response(data={'message': 'Image Size is greater than 5MB !'}, status=HTTP_400_BAD_REQUEST)

        try:
            file_serializer = FileSerializer(data=request.data)

            if file_serializer.is_valid():
                file_serializer.save()
                image_path = file_serializer.data['file']
                # recognition = detect_faces(url=image_path)
                recognition = {"number of detected faces" : "--- This feature is in developement nowadays -- "}
                data = {
                    "message": 'The image was uploaded !',
                    'result': recognition 
                }
                return Response(data=data, status=HTTP_200_OK)
            else:
                return Response(data={"message": file_serializer.errors['file'][0]}, status=HTTP_400_BAD_REQUEST)
        except Exception as e:
            print('Erorrir: ', e)
            return Response(data={"message": str(e)}, status=HTTP_500_INTERNAL_SERVER_ERROR)

class ChangeEmailView(APIView):  
    permission_classes = (IsAuthenticated,)
    def post(self, request, *args, **kwargs):
        # Retrieve the user 
        user = get_user_from_token(request)
       
        # Retriveing the new email (serialized)
        try:
            serializer = ChangeEmailSerializer(data=request.data)
            if serializer.is_valid():
                if serializer.data['email1Value'] != '' and serializer.data['email2Value'] != '':
                    if serializer.data['email1Value'] == serializer.data['email2Value']:
                        # Delete all old email Adresses
                        user.emailaddress_set.all().delete()
                        print(' Check remaining EmailAdresses' ,user.emailaddress_set.all())

                        # Set new email
                        user.email=serializer.data['email2Value']
                        user.save()
                        return Response(data={'message': 'Email was succesfuly updated !', 'type': 'success'}, status=HTTP_200_OK)
                    else:
                        return Response(data={'message': 'both emails must be the same !', 'type': 'danger'}, status=HTTP_400_BAD_REQUEST)
                else:
                    return Response(data={'message': 'both emails must be filled !', 'type': 'danger'}, status=HTTP_400_BAD_REQUEST)
            else:
                 return Response(data={'message': 'receive invalid data !', 'type': 'danger'}, status=HTTP_400_BAD_REQUEST)

        except Exception as e:
            print('Error: ', e)
            return Response(data={'message': str(e)}, status=HTTP_500_INTERNAL_SERVER_ERROR)
                  
class GetUserEmailView(APIView):
    '''
    the function recieve GET request
    Based on the Token in the headers, returns the user's email
    '''
    permission_classes = (IsAuthenticated,)
    
    def get(self, request, *args, **kwargs):
        user = get_user_from_token(request)
        obj = {'email': user.email}
        print('the new email form backend: ', obj)
        return Response(obj, status=HTTP_200_OK)

class ResetPasswordAPIView(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request, *args, **kwargs):
        request_user = get_user_from_token(request)

        parsed_password = ChangePasswordSerializer(data=request.data)
        if parsed_password.is_valid():
            current_password = parsed_password.data['current_password']
            password1 = parsed_password.data['password1']
            password2 = parsed_password.data['password2']


            if password1 == password2:
                auth_user = authenticate(username=request_user.username, password=current_password)
                if auth_user != None:
                    # change user's password
                    request_user.set_password(password2)
                    request_user.save()
                    return Response(data={'Response message': 'Success !'}, status=HTTP_200_OK)
                else:
                    return Response(data={'Response message': 'Current Password is wrong !'}, status=HTTP_400_BAD_REQUEST)
                    
            else:
                return Response(data={'Response message': 'passwords are not the same !'}, status=HTTP_400_BAD_REQUEST)

        else:
            
            return Response(data={'Response message': 'Data is not valid'}, status=HTTP_400_BAD_REQUEST)
    
class UserBillingDetailsView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        user = get_user_from_token(request)
        membership = user.membership



        # count All API requests since the begging of the month
        today = datetime.datetime.now() #today
        month_start = datetime.date(today.year, today.month, 1) # the beggining of the month
        tracked_request_count = TrackedRequest.objects.filter(user=user, timestamp__gte=month_start).count()

        try:
            # Callculate due
            amount_due = 0
            if user.is_member:
                # USE API to check the monthly due
                amount_due = stripe.Invoice.upcoming(
                    customer=user.stripe_customer_id)['amount_due'] / 100
                print('user.stripe_customer_id:  ', user.stripe_customer_id)
        except Exception as e:
             obj = {'membershipType': f"Internal Error: {str(e)}"}
             return Response(data=obj, status=HTTP_500_INTERNAL_SERVER_ERROR)



        # object to return
        obj = {
            'membershipType': membership.get_type_display(),    
            'free_trial_end_date': membership.end_date,
            'next_billing_date': membership.end_date,
            'api_request_count': tracked_request_count, 
            'amount_due': amount_due 
        }

        return Response(data=obj, status=HTTP_200_OK)

class CancelSubscriptionView(APIView):
    permission_classes = (IsMember,)

    def post(self, request, *args, **kwargs):
        user = get_user_from_token(request)
        membership = user.membership

        # check if the user is under membership
        if membership.type == 'M' and not user.on_free_trial:

            try:
                # update stripe subscription
                sub = stripe.Subscription.retrieve(membership.stripe_subscription_id)
                sub.delete()
            except Exception as e:
                return Response({"message": f"We could't cancel the subcription: {str(e)}"}, status=HTTP_500_INTERNAL_SERVER_ERROR)


            # update user instance
            user.is_member = False
            user.on_free_trial = False 
            user.save()

            # update the membership
            membership.type = 'N'
            membership.save()

saas_02/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

saas_02/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

saas_02/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% block title %}SAAS_02{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Facial Recognition API" />
    <meta name="author" content="Tzur Ben Shoshan" />

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link defer href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
      integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet" />

    <link rel="stylesheet" href="{% static 'loader/loader.css' %}">
    {% endblock %}

    {% block addcss %}
      
    {% endblock addcss %}
    
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {%block javascript %}
    <!-- Bootstrap JS -->
    <script
    defer
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
      crossorigin="anonymous"
    ></script>
    <script
    defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
      integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
      crossorigin="anonymous"
    ></script>

   
    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}
  </head>

  <body>
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
          <button
            class="navbar-toggler navbar-toggler-right"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="#!"><strong>{{ request.user.username }}</strong></a>
          {% else %}
            <a class="navbar-brand" href="{% url 'home' %}">SAAS_02</a>
          {% endif %}

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}"
                  >Home <span class="visually-hidden">(current)</span></a
                >
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:demo' %}"
                  >{% translate "Demo" %}</a
                >
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle"  role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Account
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'core:password' %}">Password</a></li>
                  <li><a class="dropdown-item" href="{% url 'account_email' %}">Email</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:billing' %}">Billing</a></li>
                  <li><a class="dropdown-item" href="{% url 'core:api-key' %}">API Key</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% translate "Log Out" %}</a></li>
                </ul>
              </li>

              {% else %} {% if ACCOUNT_ALLOW_REGISTRATION %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a
                  id="sign-up-link"
                  class="nav-link"
                  href="{% url 'account_signup' %}"
                  >{% translate "Sign Up" %}</a
                >
              </li>
              {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a
                  id="log-in-link"
                  class="nav-link"
                  href="{% url 'account_login' %}"
                  >{% translate "Sign In" %}</a
                >
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">
      <div id="message">
          {% if messages %} {% for message in messages %}
        <div
          class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% endfor %} {% endif %}
      </div>
    

      <br />

      {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
      
      {% endblock content %}
    </div>
    <!-- /container -->

    {% block modal %}
    
    {% endblock modal %} {% block inline_javascript %}
    {%comment %} Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener("DOMContentLoaded", () => {
        /* Run whatever you want */
      });
    </script>
    {% endcomment %} {% endblock inline_javascript %}
  </body>
</html>